# Context Path
#server.servlet.context-path: /erp

# Azure
# yaml 프로퍼티를 사용하여 properties 설정하기
# classpath: spring src/main ??? ?? ??? ??? ? ?? ???
spring:
  config.import: "optional:classpath:app-dbms.yml, optional:classpath:app-logger.yml"
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:static/
      add-mappings: true


## DB connection setting
#  datasource:
#    driver-class-name: "com.mysql.cj.jdbc.Driver"
#    url: "jdbc:mysql://localhost:3306/naraDB"
#    username: root
#    password: "!Biz12341234"


#  # JPA Setting
#  jpa:
#    hibernate:
#      ddl-aut: create
#
#    # bulk data insert or update Batch Process Enable ? ?????? ???? ?
#      jdbc:
#        batch_size: 100
#      order_insert: true
#      order_update: true
#
#    database: mysql
#    database-plattform: "org.hibernate.dialect.MySQL8Dialect"
#
#    # SQL Logger
#    show-sql: true
#    ### 계층구조가 없을 떄 기존방식으로 냅둬도 크게 불편하지 않음
#    properties.hibernate.format_sql: true

#    # Logger Setting
#    spring.output.ansi.enabled: ALWAYS
#    logging:
#      level:
#        root: info
#        com.callor.spring: debug